routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/mail', function () {
    return view('mail.mail');
});
Route::get('/api-menu','MenuController@index')->name('api.menu');

Route::get('/search', 'SearchController@search')->name('search');
Route::get('change-language/{locale}', 'LanguageController@changeLanguage')->name('user.change-language');
//New and event
Route::get('/', 'CompanyController@index')->name('homepage');
Route::get('/new', 'PostController@index')->name("new.index");
Route::get('/event', 'PostController@event')->name('client.event.index');
Route::get('/event/{id}', 'PostController@showEvent')->name('event.show');
Route::get('/new/{id}/{slug}', 'PostController@showNew');
Route::get('/api/new', 'PostController@getDataModal')->name('api.new');

// download

Route::post('/download','PostController@download')->name('download');

//page
Route::get('/about', 'Controller@about')->name('about.index');
Route::get('/support', 'Controller@support')->name('support');
Route::get('/asean', 'Controller@asean')->name('asean');
//end page

Route::get('/api/search-event-year','PostController@apiShowEvent')->name('apiShowEvent');

//b2b search
Route::get('/search-b2b', 'SearchController@searchB2b')->name('searchB2b');
//new search
Route::get('/search-new', 'SearchController@searchNew')->name('searchNew');
Route::get('/search-event', 'SearchController@searchEvent')->name('searchEvent');

//showroom
Route::get('/search-showroom', 'SearchController@searchShowroom')->name('search.showroom');

//Route company
Route::get('/search-company', 'SearchController@searchCompany')->name('searchCompany');

Route::get('/share-room','Controller@shareroom')->name('client.share-room');
//mobile
Route::group(['prefix' => 'mobile'], function () {
    Route::get('/', 'MobileController@index')->name('mobile.index');
    Route::get('/showroom/{id}', 'MobileController@showroom')->name('mobile.showroom.detail');
    Route::get('/showroom', 'MobileController@showroomAll')->name('mobile.showroom');
    Route::get('/new', 'MobileController@showNew')->name('mobile.new');
    Route::get('/event', 'MobileController@showEvent')->name('mobile.event');
    Route::group(['middleware' => 'auth'], function () {
        Route::get('/book', 'MobileController@showBook')->name('mobile.book');
    });
    Route::get('/company/{id}', 'MobileController@showDetailCompany')->name('mobile.company.detail');
    Route::get('/company/', 'MobileController@showCompany')->name('mobile.company');

});
//company
Route::get('/company', 'CompanyController@showList')->name('client.company.index');
Route::get('/company/{id}', 'CompanyController@show');
Route::get('/company-incubating', 'CompanyController@showIncubating')->name('company.incubating');
Route::get('/company-b2b', 'CompanyController@showB2b')->name('company.b2b');
Route::get('/company-all', 'CompanyController@showCompanyAll')->name('company.company');
//showroom
Route::get('/showroom', 'ShowroomController@index')->name('client.showroom.index');
Route::get('/showroom/{id}', 'ShowroomController@show')->name('show.detail');
//only login
Route::group(['middleware' => 'auth'], function () {
    //book
    Route::get('/api/book', 'BookController@apiShowListBook')->name('client.book.show');
    Route::get('/api/book-pdf', 'BookController@apiShowListBookPDF')->name('client.book.pdf');
    //show

    Route::get('/book/{id}', 'BookController@show')->name('client.book.index');
    Route::get('/book-lager', 'BookController@show1')->name('client.book-lager');
    Route::get('/book-small', 'BookController@show2')->name('client.book-small');
    Route::get('/book-open', 'BookController@show3')->name('client.book-open');
    //end
    Route::get('/client-book', 'BookController@book')->name('client.book.new');
    Route::get('/api/confirm-book', 'BookController@confirm')->name('book.confirm');
    Route::get('/user-account', 'BookController@bookHistory')->name('user.profile');
    Route::get('/user-update', 'UserController@update')->name('user.update');
    Route::post('/user-upload', 'UserController@uploadUser')->name('user-upload');


    //export pdf
    Route::get('/export-pdf','PdfController@index')->name('export-pdf');

});
Route::get('/booking-cancer/{id}', 'BookController@deleteBooking')->name('deleteBooking');
//only admin
Route::group(['middleware' => 'admin'], function () {
    Route::get('/admin', 'AdminCompanyController@showAdmin');
    Route::group(['prefix' => 'admin'], function () {
        Route::resource('post', 'AdminPostController');
        //list post
        Route::get('admin/event', 'AdminPostController@listEvent')->name('admin.event.list');
        Route::get('admin/history', 'AdminPostController@listHistory')->name('admin.history.list');

        Route::get('event/{event}/edit', 'AdminPostController@updateEvent')->name('event.edit');
        Route::resource('company', 'AdminCompanyController');

        Route::resource('showroom', 'AdminShowroomController');

        Route::resource('shareroom', 'AdminShareroomController');
        Route::get('event/create', 'AdminPostController@createEvent')->name('event.create');
        Route::get('count', 'AdminCompanyController@count')->name('admin.count');
        Route::get('book', 'AdminBookController@index')->name('book.index');
        Route::get('show-book-admin', 'BookController@showBackEnd')->name('book.admin');

        Route::get('/user-admin', 'UserController@list')->name('admin.user');
        Route::post('/user-change-pass', 'UserController@changePass')->name('admin.changepass');

        ///  IMPORT EXPORT
        Route::get('/export/post', 'PostImportExportController@export')->name('admin.post.export');
        Route::post('/import/post', 'PostImportExportController@importNew')->name('admin.post.importNew');

        //new
        Route::get('/post-show-new', 'AdminPostController@showDataNew')->name('admin.post.show-new');
        Route::get('/post-show-history', 'AdminPostController@showDataHistory')->name('admin.post.show-history');
        Route::get('/post-show-event', 'AdminPostController@showDataEvent')->name('admin.post.show-event');

        //company
        Route::get('/api-company-incubating-', 'AdminCompanyController@showDataIncubating')->name('api-company-incubating');
        Route::get('/api-company-b2b', 'AdminCompanyController@showDataB2b')->name('api-company-b2b');
        Route::get('/admin-b2b','AdminCompanyController@B2b')->name('admin.b2b');

        //showroom
        Route::get('/api-showroom','AdminShowroomController@showData')->name('api.showroom');

        //api book list admin
        Route::get('/api/book-list-admin','AdminBookController@showListBook')->name('api.showListBook');

        Route::resource('/admin-book','AdminBookController');

        ///user
        Route::get('/api-list-user','UserController@showDataUser')->name('api.list-user');

        // menu admin
        Route::get('/admin-menu',"AdminMenuController@index")->name('admin.menu');
        Route::get('/admin-menu-update',"AdminMenuController@update")->name('admin.menu-update');
    });
});


Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
//language

app/Http/Controllers/ShowroomController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Session;
use App;
use Config;
use App\Model\Showroom;

class ShowroomController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        App::setLocale(Session::get('locale'));
        $locale = Config::get('app.locale');
        if ($locale == null) {
            $locale = 'en';
        }
        $showroom = Showroom::paginate(10);
        return view('client.showroom.index', compact(['locale', 'showroom']));
    }


    public function show($id)
    {
        App::setLocale(Session::get('locale'));
        $locale = Config::get('app.locale');
        if ($locale == null) {
            $locale = 'en';
        }
        $showroom = Showroom::find($id);
        return view('client.showroom.detail', compact(['locale','showroom']));
    }


}

resources/views/backend/showroom/create.blade.php
@extends('backend.master_admin')
@section('content')
    <br>
    <div class="row">
        <div class="col-lg-12">
            @if(session()->has('message'))
                <div class="alert alert-success">
                    {{ session()->get('message') }}
                </div>
            @endif
        </div>
    </div>
    <div class="container mt-3">
        <h2>Create showroom</h2>
        <br>
        <!-- Nav tabs -->
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" href="#home"> <img src="{{asset('images/eng.png')}}" alt="">English</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#menu1"><img src="{{asset('images/vie.png')}}" alt="">Việt Nam</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#menu2"><img src="{{asset('images/kor.png')}}" alt="">Korean</a>
            </li>
        </ul>
        <form action="{{route('showroom.store')}}" enctype="multipart/form-data" method="post"
              style="margin-bottom: 2em">
        @csrf
        <!-- Tab panes -->
            <div class="tab-content">
                <div id="home" class="container tab-pane active"><br>
                    <div class="form-group">
                        <label>Title</label>
                        <input class="form-control"  name="title_en" id="title_en" placeholder="Title...">
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Images 1</label>
                                <input required type="file" class="from-control" name="img" id="img">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>File Pdf</label>
                                <input accept="application/pdf,application/vnd.ms-excel" type="file"
                                       class="from-control" name="file_pdf" id="file_pdf">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>File Excel</label>
                                <input accept=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel"
                                       type="file" class="from-control" name="file_excel" id="file_excel">
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="form-group">
                        <label>Content</label>
                        <textarea id="content_en" name="content_en" class="form-control" placeholder="Content..."></textarea>
                    </div>
                    <div class="form-group">
                        <label>Tel</label>
                        <input type="text" class="form-control" name="tel" placeholder="Tel...">
                    </div>
                    <div class="form-group">
                        <label>Email</label>
                        <input type="email" class="form-control" name="email" placeholder="Email...">
                    </div>
                    <div class="form-group">
                        <label>Address</label>
                        <input type="text" class="form-control" name="address" placeholder="Address...">
                    </div>
                    <div class="form-group">
                        <label for="">Description</label>
                        <textarea name="description_en" id="description_en" class="form-control" placeholder="Description..."></textarea>
                    </div>
                </div>
                <div id="menu1" class="container tab-pane fade"><br>
                    <div class="form-group">
                        <label>Title</label>
                        <input class="form-control" placeholder="title" name="title_vi" id="title_vi">
                    </div>
                    <div class="form-group">
                        <label>Content</label>
                        <textarea id="content_vi" name="content_vi" class="form-control"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="">Description</label>
                        <textarea name="description_vi" id="description_vi" class="form-control" placeholder="Description..."></textarea>
                    </div>
                </div>
                <div id="menu2" class="container tab-pane fade"><br>
                    <div class="form-group">
                        <label>Title</label>
                        <input class="form-control" placeholder="title" name="title_ko" id="title_ko">
                    </div>
                    <div class="form-group">
                        <label>Content</label>
                        <textarea id="content_ko" placeholder="Please enter detail" name="content_ko"
                                  class="form-control"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="">Description</label>
                        <textarea placeholder="Description..." name="description_ko" id="description_ko"
                                  class="form-control"></textarea>
                    </div>
                </div>
                <button style="margin-left: 1em" type="submit" class="btn btn-danger">Create</button>
                <br>
            </div>

        </form>
    </div>

    <script>
        $(document).ready(function () {
            $(".nav-tabs a").click(function () {
                $(this).tab('show');
            });
        });

        CKEDITOR.replace('content_vi', {
            uploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files&responseType=json',
            filebrowserBrowseUrl: '{{ asset('ckfinder/ckfinder.html') }}',
            filebrowserImageBrowseUrl: '{{ asset('ckfinder/ckfinder.html?type=Images') }}',
            filebrowserFlashBrowseUrl: '{{ asset('ckfinder/ckfinder.html?type=Flash') }}',
            filebrowserUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files') }}',
            filebrowserImageUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images') }}',
            filebrowserFlashUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash') }}'
        });
        CKEDITOR.replace('content_en', {
            uploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files&responseType=json',
            filebrowserBrowseUrl: '{{ asset('ckfinder/ckfinder.html') }}',
            filebrowserImageBrowseUrl: '{{ asset('ckfinder/ckfinder.html?type=Images') }}',
            filebrowserFlashBrowseUrl: '{{ asset('ckfinder/ckfinder.html?type=Flash') }}',
            filebrowserUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files') }}',
            filebrowserImageUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images') }}',
            filebrowserFlashUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash') }}'
        });
        CKEDITOR.replace('content_ko', {
            uploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files&responseType=json',
            filebrowserBrowseUrl: '{{ asset('ckfinder/ckfinder.html') }}',
            filebrowserImageBrowseUrl: '{{ asset('ckfinder/ckfinder.html?type=Images') }}',
            filebrowserFlashBrowseUrl: '{{ asset('ckfinder/ckfinder.html?type=Flash') }}',
            filebrowserUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files') }}',
            filebrowserImageUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images') }}',
            filebrowserFlashUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash') }}'
        });

        CKEDITOR.replace('description_vi', {
            uploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files&responseType=json',
            filebrowserBrowseUrl: '{{ asset('ckfinder/ckfinder.html') }}',
            filebrowserImageBrowseUrl: '{{ asset('ckfinder/ckfinder.html?type=Images') }}',
            filebrowserFlashBrowseUrl: '{{ asset('ckfinder/ckfinder.html?type=Flash') }}',
            filebrowserUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files') }}',
            filebrowserImageUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images') }}',
            filebrowserFlashUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash') }}'
        });
        CKEDITOR.replace('description_en', {
            uploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files&responseType=json',
            filebrowserBrowseUrl: '{{ asset('ckfinder/ckfinder.html') }}',
            filebrowserImageBrowseUrl: '{{ asset('ckfinder/ckfinder.html?type=Images') }}',
            filebrowserFlashBrowseUrl: '{{ asset('ckfinder/ckfinder.html?type=Flash') }}',
            filebrowserUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files') }}',
            filebrowserImageUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images') }}',
            filebrowserFlashUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash') }}'
        });
        CKEDITOR.replace('description_ko', {
            uploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files&responseType=json',
            filebrowserBrowseUrl: '{{ asset('ckfinder/ckfinder.html') }}',
            filebrowserImageBrowseUrl: '{{ asset('ckfinder/ckfinder.html?type=Images') }}',
            filebrowserFlashBrowseUrl: '{{ asset('ckfinder/ckfinder.html?type=Flash') }}',
            filebrowserUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files') }}',
            filebrowserImageUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images') }}',
            filebrowserFlashUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash') }}'
        });
    </script>

@endsection

resources/views/backend/showroom/edit.blade.php
@extends('backend.master_admin')

@section('content')
    <br>
    <div class="row">
        <div class="col-lg-12">
            @if(session()->has('message'))
                <div class="alert alert-success">
                    {{ session()->get('message') }}
                </div>
            @endif
        </div>
    </div>
    <div class="container mt-3">
        <h2>Update Show room</h2>
        <br>
        <!-- Nav tabs -->
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" href="#home"> <img src="{{asset('images/eng.png')}}" alt="">English</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#menu1"><img src="{{asset('images/vie.png')}}" alt="">Việt Nam</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#menu2"><img src="{{asset('images/kor.png')}}" alt="">Korean</a>
            </li>
        </ul>
        <form action="{{route('showroom.update', ['id' => $show->id])}}" enctype="multipart/form-data" method="POST"
              style="margin-bottom: 2em">
        {{ method_field('PUT') }}
        @csrf
        <!-- Tab panes -->
            <div class="tab-content">
                <div id="home" class="container tab-pane active"><br>
                    <div class="form-group">
                        <label>Title</label>
                        <input value="{{$show->title_en}}" class="form-control" placeholder="title" name="title_en"
                               id="title_en">
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Images</label>
                                <input type="file" class="from-control" name="img" id="img">
                            </div>

                        </div>
                        <div class="col-md-8">
                            <img style="width: 80px" src="{{asset($show->images)}}" alt="">
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>File Pdf</label>
                                <input accept="application/pdf,application/vnd.ms-excel" type="file" class="from-control" name="file_pdf" id="file_pdf">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>File Excel</label>
                                <input accept=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel"
                                       type="file" class="from-control" name="file_excel" id="file_excel">
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="form-group">
                        <label>Content</label>
                        <textarea id="content_en" name="content_en" class="form-control">{{$show->content_en}}</textarea>
                    </div>
                    <div class="form-group">
                        <label>Tel</label>
                        <input type="text" class="form-control" name="tel" placeholder="Tel..." value="{{$show->tel}}">
                    </div>
                    <div class="form-group">
                        <label>Email</label>
                        <input type="email" class="form-control" name="email" placeholder="Email..." value="{{$show->email}}">
                    </div>
                    <div class="form-group">
                        <label>Address</label>
                        <input type="text" class="form-control" name="address" placeholder="Address..." value="{{$show->address}}">
                    </div>
                    <div class="form-group">
                        <label for="">Description</label>
                        <textarea name="description_en" id="description_en" class="form-control">
                            {{$show->description_en}}
                        </textarea>
                    </div>
                </div>

                <div id="menu1" class="container tab-pane fade"><br>
                    <div class="form-group">
                        <label>Title</label>
                        <input value="{{$show->title_vi}}" class="form-control" placeholder="title" name="title_vi"
                               id="title_vi">
                    </div>
                    <div class="form-group">
                        <label>Content</label>
                        <textarea id="content_vi" name="content_vi"
                                  class="form-control">{{$show->content_vi}}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="">Description</label>
                        <textarea name="description_vi" id="description_vi" class="form-control">
                            {{$show->description_vi}}
                        </textarea>
                    </div>
                </div>
                <div id="menu2" class="container tab-pane fade"><br>
                    <div class="form-group">
                        <label>Title</label>
                        <input value="{{$show->title_ko}}" class="form-control" placeholder="title" name="title_ko" id="title_ko">
                    </div>
                    <div class="form-group">
                        <label>Content</label>
                        <textarea id="content_ko" name="content_ko" class="form-control"> {{$show->content_ko}}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="">Description</label>
                        <textarea name="description_ko" id="description_ko" class="form-control">
                            {{$show->description_ko}}
                        </textarea>
                    </div>
                </div>
                <button style="margin-left: 1em" type="submit" class="btn btn-danger">Update</button>
                <br>
            </div>

        </form>
    </div>

    <script>
        $(document).ready(function () {
            $(".nav-tabs a").click(function () {
                $(this).tab('show');
            });
        });
        CKEDITOR.replace('content_vi', {
            uploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files&responseType=json',
            filebrowserBrowseUrl: '{{ asset('ckfinder/ckfinder.html') }}',
            filebrowserImageBrowseUrl: '{{ asset('ckfinder/ckfinder.html?type=Images') }}',
            filebrowserFlashBrowseUrl: '{{ asset('ckfinder/ckfinder.html?type=Flash') }}',
            filebrowserUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files') }}',
            filebrowserImageUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images') }}',
            filebrowserFlashUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash') }}'
        });
        CKEDITOR.replace('content_en', {
            uploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files&responseType=json',
            filebrowserBrowseUrl: '{{ asset('ckfinder/ckfinder.html') }}',
            filebrowserImageBrowseUrl: '{{ asset('ckfinder/ckfinder.html?type=Images') }}',
            filebrowserFlashBrowseUrl: '{{ asset('ckfinder/ckfinder.html?type=Flash') }}',
            filebrowserUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files') }}',
            filebrowserImageUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images') }}',
            filebrowserFlashUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash') }}'
        });
        CKEDITOR.replace('content_ko', {
            uploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files&responseType=json',
            filebrowserBrowseUrl: '{{ asset('ckfinder/ckfinder.html') }}',
            filebrowserImageBrowseUrl: '{{ asset('ckfinder/ckfinder.html?type=Images') }}',
            filebrowserFlashBrowseUrl: '{{ asset('ckfinder/ckfinder.html?type=Flash') }}',
            filebrowserUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files') }}',
            filebrowserImageUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images') }}',
            filebrowserFlashUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash') }}'
        });

        CKEDITOR.replace('description_vi', {
            uploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files&responseType=json',
            filebrowserBrowseUrl: '{{ asset('ckfinder/ckfinder.html') }}',
            filebrowserImageBrowseUrl: '{{ asset('ckfinder/ckfinder.html?type=Images') }}',
            filebrowserFlashBrowseUrl: '{{ asset('ckfinder/ckfinder.html?type=Flash') }}',
            filebrowserUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files') }}',
            filebrowserImageUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images') }}',
            filebrowserFlashUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash') }}'
        });
        CKEDITOR.replace('description_en', {
            uploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files&responseType=json',
            filebrowserBrowseUrl: '{{ asset('ckfinder/ckfinder.html') }}',
            filebrowserImageBrowseUrl: '{{ asset('ckfinder/ckfinder.html?type=Images') }}',
            filebrowserFlashBrowseUrl: '{{ asset('ckfinder/ckfinder.html?type=Flash') }}',
            filebrowserUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files') }}',
            filebrowserImageUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images') }}',
            filebrowserFlashUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash') }}'
        });
        CKEDITOR.replace('description_ko', {
            uploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files&responseType=json',
            filebrowserBrowseUrl: '{{ asset('ckfinder/ckfinder.html') }}',
            filebrowserImageBrowseUrl: '{{ asset('ckfinder/ckfinder.html?type=Images') }}',
            filebrowserFlashBrowseUrl: '{{ asset('ckfinder/ckfinder.html?type=Flash') }}',
            filebrowserUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files') }}',
            filebrowserImageUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images') }}',
            filebrowserFlashUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash') }}'
        });
    </script>

@endsection