routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/mail', function () {
    return view('mail.mail');
});
Route::get('/api-menu','MenuController@index')->name('api.menu');

Route::get('/search', 'SearchController@search')->name('search');
Route::get('change-language/{locale}', 'LanguageController@changeLanguage')->name('user.change-language');
//New and event
Route::get('/', 'CompanyController@index')->name('homepage');
Route::get('/new', 'PostController@index')->name("new.index");
Route::get('/event', 'PostController@event')->name('client.event.index');
Route::get('/event/{id}', 'PostController@showEvent')->name('event.show');
Route::get('/new/{id}/{slug}', 'PostController@showNew');
Route::get('/api/new', 'PostController@getDataModal')->name('api.new');

// download

Route::post('/download','PostController@download')->name('download');

//page
Route::get('/about', 'Controller@about')->name('about.index');
Route::get('/support', 'Controller@support')->name('support');
Route::get('/asean', 'Controller@asean')->name('asean');
//end page

Route::get('/api/search-event-year','PostController@apiShowEvent')->name('apiShowEvent');

//b2b search
Route::get('/search-b2b', 'SearchController@searchB2b')->name('searchB2b');
//new search
Route::get('/search-new', 'SearchController@searchNew')->name('searchNew');
Route::get('/search-event', 'SearchController@searchEvent')->name('searchEvent');

//showroom
Route::get('/search-showroom', 'SearchController@searchShowroom')->name('search.showroom');

//Route company
Route::get('/search-company', 'SearchController@searchCompany')->name('searchCompany');

Route::get('/share-room','Controller@shareroom')->name('client.share-room');
//mobile
Route::group(['prefix' => 'mobile'], function () {
    Route::get('/', 'MobileController@index')->name('mobile.index');
    Route::get('/showroom/{id}', 'MobileController@showroom')->name('mobile.showroom.detail');
    Route::get('/showroom', 'MobileController@showroomAll')->name('mobile.showroom');
    Route::get('/new', 'MobileController@showNew')->name('mobile.new');
    Route::get('/event', 'MobileController@showEvent')->name('mobile.event');
    Route::group(['middleware' => 'auth'], function () {
        Route::get('/book', 'MobileController@showBook')->name('mobile.book');
    });
    Route::get('/company/{id}', 'MobileController@showDetailCompany')->name('mobile.company.detail');
    Route::get('/company/', 'MobileController@showCompany')->name('mobile.company');

});
//company
Route::get('/company', 'CompanyController@showList')->name('client.company.index');
Route::get('/company/{id}', 'CompanyController@show');
Route::get('/company-incubating', 'CompanyController@showIncubating')->name('company.incubating');
Route::get('/company-b2b', 'CompanyController@showB2b')->name('company.b2b');
Route::get('/company-all', 'CompanyController@showCompanyAll')->name('company.company');
//showroom
Route::get('/showroom', 'ShowroomController@index')->name('client.showroom.index');
Route::get('/showroom/{id}', 'ShowroomController@show')->name('show.detail');
//only login
Route::group(['middleware' => 'auth'], function () {
    //book
    Route::get('/api/book', 'BookController@apiShowListBook')->name('client.book.show');
    Route::get('/api/book-pdf', 'BookController@apiShowListBookPDF')->name('client.book.pdf');
    //show

    Route::get('/book/{id}', 'BookController@show')->name('client.book.index');
    Route::get('/book-lager', 'BookController@show1')->name('client.book-lager');
    Route::get('/book-small', 'BookController@show2')->name('client.book-small');
    Route::get('/book-open', 'BookController@show3')->name('client.book-open');
    //end
    Route::get('/client-book', 'BookController@book')->name('client.book.new');
    Route::get('/api/confirm-book', 'BookController@confirm')->name('book.confirm');
    Route::get('/user-account', 'BookController@bookHistory')->name('user.profile');
    Route::get('/user-update', 'UserController@update')->name('user.update');
    Route::post('/user-upload', 'UserController@uploadUser')->name('user-upload');


    //export pdf
    Route::get('/export-pdf','PdfController@index')->name('export-pdf');

});
Route::get('/booking-cancer/{id}', 'BookController@deleteBooking')->name('deleteBooking');
//only admin
Route::group(['middleware' => 'admin'], function () {
    Route::get('/admin', 'AdminCompanyController@showAdmin');
    Route::group(['prefix' => 'admin'], function () {
        Route::resource('post', 'AdminPostController');
        //list post
        Route::get('admin/event', 'AdminPostController@listEvent')->name('admin.event.list');
        Route::get('admin/history', 'AdminPostController@listHistory')->name('admin.history.list');

        Route::get('event/{event}/edit', 'AdminPostController@updateEvent')->name('event.edit');
        Route::resource('company', 'AdminCompanyController');

        Route::resource('showroom', 'AdminShowroomController');

        Route::resource('shareroom', 'AdminShareroomController');
        Route::get('event/create', 'AdminPostController@createEvent')->name('event.create');
        Route::get('count', 'AdminCompanyController@count')->name('admin.count');
        Route::get('book', 'AdminBookController@index')->name('book.index');
        Route::get('show-book-admin', 'BookController@showBackEnd')->name('book.admin');

        Route::get('/user-admin', 'UserController@list')->name('admin.user');
        Route::post('/user-change-pass', 'UserController@changePass')->name('admin.changepass');

        ///  IMPORT EXPORT
        Route::get('/export/post', 'PostImportExportController@export')->name('admin.post.export');
        Route::post('/import/post', 'PostImportExportController@importNew')->name('admin.post.importNew');

        //new
        Route::get('/post-show-new', 'AdminPostController@showDataNew')->name('admin.post.show-new');
        Route::get('/post-show-history', 'AdminPostController@showDataHistory')->name('admin.post.show-history');
        Route::get('/post-show-event', 'AdminPostController@showDataEvent')->name('admin.post.show-event');

        //company
        Route::get('/api-company-incubating-', 'AdminCompanyController@showDataIncubating')->name('api-company-incubating');
        Route::get('/api-company-b2b', 'AdminCompanyController@showDataB2b')->name('api-company-b2b');
        Route::get('/admin-b2b','AdminCompanyController@B2b')->name('admin.b2b');

        //showroom
        Route::get('/api-showroom','AdminShowroomController@showData')->name('api.showroom');

        //api book list admin
        Route::get('/api/book-list-admin','AdminBookController@showListBook')->name('api.showListBook');

        Route::resource('/admin-book','AdminBookController');

        ///user
        Route::get('/api-list-user','UserController@showDataUser')->name('api.list-user');

        // menu admin
        Route::get('/admin-menu',"AdminMenuController@index")->name('admin.menu');
        Route::get('/admin-menu-update',"AdminMenuController@update")->name('admin.menu-update');
    });
});


Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
//language

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use  App\Repositories\Eloquent\CompanyEloquentRepository;
use  App\Repositories\Eloquent\PostEloquentRepository;
use  App\Repositories\Eloquent\ShowroomEloquentRepository;
use Session;
use App;
use Config;
use Illuminate\Support\Facades\DB;
use App\Model\Post;
use App\Model\Company;

class CompanyController extends Controller
{
    protected $companyRepository;
    protected $postRepository;
    protected $roomRepository;

    function __construct(
        CompanyEloquentRepository $companyRepository,
        PostEloquentRepository $postRepository,
        ShowroomEloquentRepository $roomRepository
    )
    {
        // parent::__construct();
        $this->companyRepository = $companyRepository;
        $this->postRepository = $postRepository;
        $this->roomRepository = $roomRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        App::setLocale(Session::get('locale'));
        $locale = Config::get('app.locale');
        if ($locale == null) {
            $locale = 'en';
        }
        $b = "select * from companies where cate_id = 3 ORDER BY RAND() limit 10 ";
        $b2b_matching = DB::select(DB::raw($b));

        $i = "select * from companies where cate_id = 2 ORDER BY RAND() limit 10";
        $incubating = DB::select(DB::raw($i));

        $h = "select * from posts where cate_id = 3 ORDER BY RAND() limit 10";
        $history = DB::select(DB::raw($h));

        $e = "select * from posts p where p.cate_id  != 3   ORDER BY p.created_at DESC limit 10";
        $event = DB::select(DB::raw($e));
//        return $event;
        $s = "select * from showrooms ORDER BY RAND() limit 10";
        $showrom = DB::select(DB::raw($s));
        return view('client', compact(['b2b_matching', 'incubating', 'showrom', 'locale', 'event', 'history']));
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function showList()
    {
        App::setLocale(Session::get('locale'));
        $locale = Config::get('app.locale');
        if ($locale == null) {
            $locale = 'en';
        }
        $b = "
        SELECT *
        FROM companies c
        WHERE c.cate_id = 3
        ORDER BY created_at DESC limit 10";
        $b2b_matching = DB::select(DB::raw($b));

        $i = "SELECT *
        FROM companies c
        WHERE c.cate_id = 2
        ORDER BY created_at DESC limit 10";
        $incubating = DB::select(DB::raw($i));

        return view('client.company.company', compact(['incubating', 'b2b_matching', 'locale']));
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        App::setLocale(Session::get('locale'));
        $locale = Config::get('app.locale');
        if ($locale == null) {
            $locale = 'en';
        }
        $company = $this->companyRepository->find($id);
        // return $company;
        return view('client.company.detail', compact(['company', 'locale']));
    }

    public function showIncubating()
    {
        App::setLocale(Session::get('locale'));
        $locale = Config::get('app.locale');
        if ($locale == null) {
            $locale = 'en';
        }
        $incubating = Company::where('cate_id', 2)->paginate('10');
        return view('client.company.incubating', compact(['incubating', 'locale']));
    }

    public function showCompanyAll()
    {
        App::setLocale(Session::get('locale'));
        $locale = Config::get('app.locale');
        if ($locale == null) {
            $locale = 'en';
        }
        $company = Company::where('cate_id', 1)->paginate('10');
        return view('client.company.company-all', compact(['company', 'locale']));
    }

    public function showB2b()
    {
        App::setLocale(Session::get('locale'));
        $locale = Config::get('app.locale');
        if ($locale == null) {
            $locale = 'en';
        }
        $b2b = Company::where('cate_id', 3)->paginate('10');
        return view('client.company.b2b', compact(['b2b', 'locale']));
    }

}

resources/views/backend/company/b2bmatching.blade.php
@extends('backend.master_admin')
@section('content')
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <script src="//code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="//cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js"></script>

    <br>
    <div class="row">
        <div class="col-lg-12">
            @if(session()->has('message'))
                <div class="alert alert-success">
                    {{ session()->get('message') }}
                </div>
            @endif
        </div>
    </div>
    <div class="container mt-3">
        <h2>List B2b matching</h2>
        {{--<div class="row">--}}
            {{--<div class="col-md-12" style="margin-bottom: 2em;margin-top: 2em">--}}
                {{--<a class="btn btn-primary float-left" href="{{asset('uploads/posts.xlsx')}}"><span><i--}}
                                {{--class="fas fa-file-download"></i></span> Download Template</a>--}}
                {{--<form style="float: right" class="form-inline" action="{{ route('admin.post.importNew') }}"--}}
                      {{--method="POST"--}}
                      {{--enctype="multipart/form-data">--}}
                    {{--@csrf--}}
                    {{--<div class="form-group mb-2">--}}
                        {{--<input required--}}
                               {{--accept=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel"--}}
                               {{--type="file" name="file" class="form-control">--}}
                    {{--</div>--}}
                    {{--<button class="btn btn-success"><i class="fas fa-upload"></i> Import</button>--}}
                {{--</form>--}}
            {{--</div>--}}
        {{--</div>--}}
        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-company">
            <thead>
            <tr>
                <th>id</th>
                <th>Title (Eng)</th>
                <th>Title (Ko)</th>
                <th>Address</th>
                <th colspan="2"></th>
            </tr>
            </thead>
        </table>
    </div>

@endsection
@push('script')

    <script>
        $(function () {
            $('#dataTables-company').DataTable({
                async: true,
                ajax: {
                    "url": "{{ route('api-company-b2b') }}",
                    "type": "GET",
                    "headers": {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                },
                columns: [
                    {data: 'id'},
                    {data: 'company_name_en', orderable: true, searchable: true},
                    {data: 'company_name_ko'},
                    {data: 'address'},
                    {data: 'action', name: 'action', orderable: false, searchable: false},
                ]
            });
        });

        function confirmDelete($id) {
            if (confirm("Are you sure you want to delete this item?") == true) {
                $(document).find('#frm_delete_' + $id).submit();
            } else {
                return false
            }
        }
    </script>
@endpush

resources/views/backend/company/create.blade.php
@extends('backend.master_admin')
@section('content')
    <br>
    <div class="row">
        <div class="col-lg-12">
            @if(session()->has('message'))
                <div class="alert alert-success">
                    {{ session()->get('message') }}
                </div>
            @endif
        </div>
    </div>
    <div class="container mt-3">
        <h2>Create company</h2>
        <br>
        <form action="{{route('company.store')}}" enctype="multipart/form-data" method="post"
              style="margin-bottom: 2em">
            @csrf
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="">Images</label>
                        <input value="uploads/noimage.jpg" type="file" class="from-control" name="img" id="img">
                    </div>
                </div>
                <div class="col-md-6">
                    <label for="">Category</label>
                    <select onchange="displayForm()"  name="cate_id" class="form-control" id="cate_id" required>
                        <option >Please select company type</option>
                        <option value="2">Incubating</option>
                        <option value="3">B2b matching</option>
                    </select>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label>File Pdf</label>
                        <input accept="application/pdf,application/vnd.ms-excel" type="file"
                               class="from-control" name="file_pdf" id="file_pdf">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label>File Excel</label>
                        <input accept=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel"
                               type="file" class="from-control" name="file_excel" id="file_excel">
                    </div>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label>Company name (Eng)</label>
                        <input required class="form-control" type="text" value="" name="company_name_en">
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label>Company name (Ko)</label>
                        <input class="form-control" type="text" value="" name="company_name_ko">
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label>Company name (Vi)</label>
                        <input class="form-control" type="text" value="" name="company_name_vi">
                    </div>
                </div>
            </div>
            <div class="row">
                <div id="hide1">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label>Company tel</label>
                            <input class="form-control" type="text" value="" name="tel1" >
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label>Kind</label>
                            <input class="form-control" type="text" value="" name="kind">
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label>Date</label>
                        <input class="form-control" type="date" value="" name="date" required>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label>Company type</label>
                        <input class="form-control" type="text" value="" name="type">
                    </div>
                </div>

            </div>
            <div id="hide2">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Owner name</label>
                            <input class="form-control" type="text" value="" name="owmer">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Owner tel</label>
                            <input class="form-control" type="text" value="" name="otel" >
                        </div>
                    </div>

                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Manager</label>
                            <input class="form-control" type="text" value="" name="manger">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Manager tel</label>
                            <input class="form-control" type="text" value="" name="mtel">
                        </div>
                    </div>

                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Email 1</label>
                        <input class="form-control" type="text" value="" name="email1">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Email 2</label>
                        <input class="form-control" type="text" value="" name="email2">
                    </div>
                </div>

            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label>Website</label>
                        <input class="form-control" type="text" value="" name="website">
                    </div>
                </div>
            </div>
            <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label>About us En</label>
                            <textarea class="form-control"  name="about_us_en"></textarea>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label>About us Ko</label>
                            <textarea class="form-control"  name="about_us_ko"></textarea>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label>About us Vi</label>
                            <textarea class="form-control"  name="about_us_vi"></textarea>
                        </div>
                    </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Number of korean employee</label>
                        <input class="form-control" type="text" value="" name="emp_ko">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Number of Viet Nam employee</label>
                        <input class="form-control" type="text" value="" name="emp_VN">
                    </div>
                </div>
            </div>
            <div class="row">

                <div class="col-md-6">
                    <div class="form-group">
                        <label>Area</label>
                        <input class="form-control" type="text" value="" name="area">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Location</label>
                        <input class="form-control" type="text" value="" name="location">
                    </div>
                </div>

            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label>Address</label>
                        <input class="form-control" type="text" value="" name="address">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label>Service (Eng)</label>
                        <input class="form-control" type="text" value="" name="service_en">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label>Service (Vi)</label>
                        <input class="form-control" type="text" value="" name="service_vi">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label>Service (Ko)</label>
                        <input class="form-control" type="text" value="" name="service_ko">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <button type="submit" class="btn btn-danger">Create</button>
                </div>
            </div>
        </form>
    </div>
    <script>
        function displayForm(id)
        {
            var select_id = document.getElementById("cate_id");
            console.log(select_id.options[select_id.selectedIndex].value)
            if(select_id.options[select_id.selectedIndex].value == 2){
                $("#hide1").hide();
                $("#hide2").hide();
            }else {
                $("#hide1").show();
                $("#hide2").show();
            }
        }
    </script>

@endsection

resources/views/backend/company/list.blade.php
@extends('backend.master_admin')
@section('content')
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <script src="//code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="//cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js"></script>

    <br>
    <div class="row">
        <div class="col-lg-12">
            @if(session()->has('message'))
                <div class="alert alert-success">
                    {{ session()->get('message') }}
                </div>
            @endif
        </div>
    </div>
    <div class="container mt-3">
        <h2>List Incubating</h2>
        {{--<div class="row">--}}
            {{--<div class="col-md-12" style="margin-bottom: 2em;margin-top: 2em">--}}
                {{--<a class="btn btn-primary float-left" href="{{asset('uploads/posts.xlsx')}}"><span><i--}}
                                {{--class="fas fa-file-download"></i></span> Download Template</a>--}}
                {{--<form style="float: right" class="form-inline" action="{{ route('admin.post.importNew') }}"--}}
                      {{--method="POST"--}}
                      {{--enctype="multipart/form-data">--}}
                    {{--@csrf--}}
                    {{--<div class="form-group mb-2">--}}
                        {{--<input required--}}
                               {{--accept=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel"--}}
                               {{--type="file" name="file" class="form-control">--}}
                    {{--</div>--}}
                    {{--<button class="btn btn-success"><i class="fas fa-upload"></i> Import</button>--}}
                {{--</form>--}}
            {{--</div>--}}
        {{--</div>--}}
        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-company">
            <thead>
            <tr>
                <th>id</th>
                <th>Title (Eng)</th>
                <th>Title (Ko)</th>
                <th>Address</th>
                <th colspan="2"></th>
            </tr>
            </thead>
        </table>
    </div>

@endsection
@push('script')

    <script>
        $(function () {
            $('#dataTables-company').DataTable({
                async: true,
                ajax: {
                    "url": "{{ route('api-company-incubating') }}",
                    "type": "GET",
                    "headers": {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                },
                columns: [
                    {data: 'id'},
                    {data: 'company_name_en', orderable: true, searchable: true},
                    {data: 'company_name_ko'},
                    {data: 'address'},
                    {data: 'action', name: 'action', orderable: false, searchable: false},
                ]
            });
        });

        function confirmDelete($id) {
            if (confirm("Are you sure you want to delete this item?") == true) {
                $(document).find('#frm_delete_' + $id).submit();
            } else {
                return false
            }
        }
    </script>
@endpush